// Autogenerated code by VS toolbox. Event-methods are in GameForm.cs
namespace Poker_Game {
    partial class GameForm {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
       
        private void InitializeComponent() {
            this.buttonQuitToMenu = new System.Windows.Forms.Button();
            this.buttonRaise = new System.Windows.Forms.Button();
            this.buttonCall = new System.Windows.Forms.Button();
            this.buttonFold = new System.Windows.Forms.Button();
            this.buttonCheck = new System.Windows.Forms.Button();
            this.playerName = new System.Windows.Forms.Label();
            this.labelPlayerStack = new System.Windows.Forms.Label();
            this.labelTablePot = new System.Windows.Forms.Label();
            this.labelAI = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // buttonQuitToMenu
            // 
            this.buttonQuitToMenu.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonQuitToMenu.Location = new System.Drawing.Point(1105, 13);
            this.buttonQuitToMenu.Margin = new System.Windows.Forms.Padding(4);
            this.buttonQuitToMenu.Name = "buttonQuitToMenu";
            this.buttonQuitToMenu.Size = new System.Drawing.Size(194, 46);
            this.buttonQuitToMenu.TabIndex = 0;
            this.buttonQuitToMenu.Text = "Quit to Main Menu";
            this.buttonQuitToMenu.UseVisualStyleBackColor = true;
            this.buttonQuitToMenu.Click += new System.EventHandler(this.buttonQuitToMenu_Click);
            // 
            // buttonRaise
            // 
            this.buttonRaise.BackColor = System.Drawing.Color.Maroon;
            this.buttonRaise.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonRaise.Font = new System.Drawing.Font("Microsoft Sans Serif", 22.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonRaise.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.buttonRaise.Location = new System.Drawing.Point(556, 724);
            this.buttonRaise.Margin = new System.Windows.Forms.Padding(4);
            this.buttonRaise.Name = "buttonRaise";
            this.buttonRaise.Size = new System.Drawing.Size(147, 73);
            this.buttonRaise.TabIndex = 1;
            this.buttonRaise.Text = "Raise";
            this.buttonRaise.UseVisualStyleBackColor = false;
            this.buttonRaise.Click += new System.EventHandler(this.buttonRaise_Click);
            // 
            // buttonCall
            // 
            this.buttonCall.BackColor = System.Drawing.Color.Maroon;
            this.buttonCall.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonCall.Font = new System.Drawing.Font("Microsoft Sans Serif", 22.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonCall.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.buttonCall.Location = new System.Drawing.Point(401, 724);
            this.buttonCall.Margin = new System.Windows.Forms.Padding(4);
            this.buttonCall.Name = "buttonCall";
            this.buttonCall.Size = new System.Drawing.Size(147, 73);
            this.buttonCall.TabIndex = 2;
            this.buttonCall.Text = "Call";
            this.buttonCall.UseVisualStyleBackColor = false;
            this.buttonCall.Click += new System.EventHandler(this.buttonCall_Click);
            // 
            // buttonFold
            // 
            this.buttonFold.BackColor = System.Drawing.Color.Red;
            this.buttonFold.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.buttonFold.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonFold.Font = new System.Drawing.Font("Microsoft Sans Serif", 22.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonFold.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.buttonFold.Location = new System.Drawing.Point(13, 724);
            this.buttonFold.Margin = new System.Windows.Forms.Padding(4);
            this.buttonFold.Name = "buttonFold";
            this.buttonFold.Size = new System.Drawing.Size(147, 73);
            this.buttonFold.TabIndex = 3;
            this.buttonFold.Text = "Fold";
            this.buttonFold.UseVisualStyleBackColor = false;
            // 
            // buttonCheck
            // 
            this.buttonCheck.BackColor = System.Drawing.Color.Maroon;
            this.buttonCheck.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonCheck.Font = new System.Drawing.Font("Microsoft Sans Serif", 22.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonCheck.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.buttonCheck.Location = new System.Drawing.Point(246, 724);
            this.buttonCheck.Margin = new System.Windows.Forms.Padding(4);
            this.buttonCheck.Name = "buttonCheck";
            this.buttonCheck.Size = new System.Drawing.Size(147, 73);
            this.buttonCheck.TabIndex = 4;
            this.buttonCheck.Text = "Check";
            this.buttonCheck.UseVisualStyleBackColor = false;
            this.buttonCheck.Click += new System.EventHandler(this.buttonCheck_Click);
            // 
            // playerName
            // 
            this.playerName.BackColor = System.Drawing.Color.Transparent;
            this.playerName.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.playerName.Font = new System.Drawing.Font("Microsoft Sans Serif", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.playerName.ForeColor = System.Drawing.Color.White;
            this.playerName.Location = new System.Drawing.Point(715, 684);
            this.playerName.Name = "playerName";
            this.playerName.Size = new System.Drawing.Size(190, 40);
            this.playerName.TabIndex = 5;
            this.playerName.Text = "Name";
            // 
            // labelPlayerStack
            // 
            this.labelPlayerStack.BackColor = System.Drawing.Color.Transparent;
            this.labelPlayerStack.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.labelPlayerStack.Font = new System.Drawing.Font("Microsoft Sans Serif", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelPlayerStack.ForeColor = System.Drawing.Color.White;
            this.labelPlayerStack.Location = new System.Drawing.Point(715, 724);
            this.labelPlayerStack.Name = "labelPlayerStack";
            this.labelPlayerStack.Size = new System.Drawing.Size(190, 60);
            this.labelPlayerStack.TabIndex = 6;
            this.labelPlayerStack.Text = "Stack";
            // 
            // labelTablePot
            // 
            this.labelTablePot.BackColor = System.Drawing.Color.Transparent;
            this.labelTablePot.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.labelTablePot.Font = new System.Drawing.Font("Microsoft Sans Serif", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelTablePot.ForeColor = System.Drawing.Color.White;
            this.labelTablePot.Location = new System.Drawing.Point(551, 563);
            this.labelTablePot.Name = "labelTablePot";
            this.labelTablePot.Size = new System.Drawing.Size(207, 46);
            this.labelTablePot.TabIndex = 7;
            this.labelTablePot.Text = "Pot";
            // 
            // labelAI
            // 
            this.labelAI.BackColor = System.Drawing.Color.Transparent;
            this.labelAI.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.labelAI.Font = new System.Drawing.Font("Microsoft Sans Serif", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelAI.ForeColor = System.Drawing.Color.White;
            this.labelAI.Location = new System.Drawing.Point(402, 21);
            this.labelAI.Name = "labelAI";
            this.labelAI.Size = new System.Drawing.Size(178, 120);
            this.labelAI.TabIndex = 8;
            this.labelAI.Text = "AI";
            // 
            // GameForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.BackColor = System.Drawing.SystemColors.ActiveCaption;
            this.BackgroundImage = global::Poker_Game.Properties.Resources.PokerBord;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(1312, 814);
            this.Controls.Add(this.labelAI);
            this.Controls.Add(this.labelTablePot);
            this.Controls.Add(this.labelPlayerStack);
            this.Controls.Add(this.playerName);
            this.Controls.Add(this.buttonCheck);
            this.Controls.Add(this.buttonFold);
            this.Controls.Add(this.buttonCall);
            this.Controls.Add(this.buttonRaise);
            this.Controls.Add(this.buttonQuitToMenu);
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.Name = "GameForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Game Window";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Button buttonQuitToMenu;
        private System.Windows.Forms.Button buttonRaise;
        private System.Windows.Forms.Button buttonCall;
        private System.Windows.Forms.Button buttonFold;
        private System.Windows.Forms.Button buttonCheck;
        private System.Windows.Forms.Label playerName;
        private System.Windows.Forms.Label labelPlayerStack;
        private System.Windows.Forms.Label labelTablePot;
        private System.Windows.Forms.Label labelAI;
    }
}