// Autogenerated code by VS toolbox. Event-methods are in Form1.cs
namespace Poker_Game
{
    partial class SettingsForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.buttonStartGame = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.textboxName = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.numberOfPlayersTrackBar = new System.Windows.Forms.TrackBar();
            this.potSizeTrackBar = new System.Windows.Forms.TrackBar();
            this.blindSizeTrackBar = new System.Windows.Forms.TrackBar();
            this.numberOfPlayersNumericUpDown = new System.Windows.Forms.NumericUpDown();
            this.potSizeNumericUpDown = new System.Windows.Forms.NumericUpDown();
            this.blindSizeNumericUpDown = new System.Windows.Forms.NumericUpDown();
            this.nameErrorLabel = new System.Windows.Forms.Label();
            this.timeBasedCheckBox = new System.Windows.Forms.CheckBox();
            this.roundBasedCheckBox = new System.Windows.Forms.CheckBox();
            this.blindIncreaseNumericUpDown = new System.Windows.Forms.NumericUpDown();
            this.blindIncreaseTrackBar = new System.Windows.Forms.TrackBar();
            ((System.ComponentModel.ISupportInitialize)(this.numberOfPlayersTrackBar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.potSizeTrackBar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.blindSizeTrackBar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numberOfPlayersNumericUpDown)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.potSizeNumericUpDown)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.blindSizeNumericUpDown)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.blindIncreaseNumericUpDown)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.blindIncreaseTrackBar)).BeginInit();
            this.SuspendLayout();
            // 
            // buttonStartGame
            // 
            this.buttonStartGame.Font = new System.Drawing.Font("Microsoft Sans Serif", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonStartGame.Location = new System.Drawing.Point(148, 340);
            this.buttonStartGame.Margin = new System.Windows.Forms.Padding(4);
            this.buttonStartGame.Name = "buttonStartGame";
            this.buttonStartGame.Size = new System.Drawing.Size(186, 68);
            this.buttonStartGame.TabIndex = 0;
            this.buttonStartGame.Text = "Start Game";
            this.buttonStartGame.UseVisualStyleBackColor = true;
            this.buttonStartGame.Click += new System.EventHandler(this.buttonStartGame_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(18, 21);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(146, 20);
            this.label1.TabIndex = 1;
            this.label1.Text = "Number of players";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(19, 77);
            this.label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(70, 20);
            this.label2.TabIndex = 2;
            this.label2.Text = "Pot size";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(18, 127);
            this.label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(83, 20);
            this.label3.TabIndex = 3;
            this.label3.Text = "Blind size";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(119, 295);
            this.label4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(110, 20);
            this.label4.TabIndex = 4;
            this.label4.Text = "Player Name:";
            // 
            // textboxName
            // 
            this.textboxName.Location = new System.Drawing.Point(243, 295);
            this.textboxName.Margin = new System.Windows.Forms.Padding(4);
            this.textboxName.Name = "textboxName";
            this.textboxName.Size = new System.Drawing.Size(132, 26);
            this.textboxName.TabIndex = 5;
            this.textboxName.Text = "Enter Name";
            this.textboxName.Enter += new System.EventHandler(this.textboxName_Enter);
            this.textboxName.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.textbox_CheckChange);
            this.textboxName.Leave += new System.EventHandler(this.textboxName_Leave);
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(16, 185);
            this.label5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(116, 20);
            this.label5.TabIndex = 6;
            this.label5.Text = "Blind Increase";
            // 
            // numberOfPlayersTrackBar
            // 
            this.numberOfPlayersTrackBar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.numberOfPlayersTrackBar.Location = new System.Drawing.Point(134, 21);
            this.numberOfPlayersTrackBar.Margin = new System.Windows.Forms.Padding(4);
            this.numberOfPlayersTrackBar.Maximum = 2;
            this.numberOfPlayersTrackBar.Minimum = 2;
            this.numberOfPlayersTrackBar.Name = "numberOfPlayersTrackBar";
            this.numberOfPlayersTrackBar.Size = new System.Drawing.Size(240, 56);
            this.numberOfPlayersTrackBar.TabIndex = 7;
            this.numberOfPlayersTrackBar.Value = 2;
            this.numberOfPlayersTrackBar.ValueChanged += new System.EventHandler(this.numberOfPlayersTrackBar_ValueChanged);
            // 
            // potSizeTrackBar
            // 
            this.potSizeTrackBar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.potSizeTrackBar.Location = new System.Drawing.Point(135, 72);
            this.potSizeTrackBar.Margin = new System.Windows.Forms.Padding(4);
            this.potSizeTrackBar.Maximum = 10000;
            this.potSizeTrackBar.Minimum = 100;
            this.potSizeTrackBar.Name = "potSizeTrackBar";
            this.potSizeTrackBar.Size = new System.Drawing.Size(240, 56);
            this.potSizeTrackBar.TabIndex = 8;
            this.potSizeTrackBar.Value = 1000;
            this.potSizeTrackBar.ValueChanged += new System.EventHandler(this.potSizeTrackBar_ValueChanged);
            // 
            // blindSizeTrackBar
            // 
            this.blindSizeTrackBar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.blindSizeTrackBar.Location = new System.Drawing.Point(134, 121);
            this.blindSizeTrackBar.Margin = new System.Windows.Forms.Padding(4);
            this.blindSizeTrackBar.Maximum = 1000;
            this.blindSizeTrackBar.Minimum = 10;
            this.blindSizeTrackBar.Name = "blindSizeTrackBar";
            this.blindSizeTrackBar.Size = new System.Drawing.Size(240, 56);
            this.blindSizeTrackBar.TabIndex = 9;
            this.blindSizeTrackBar.Value = 50;
            this.blindSizeTrackBar.ValueChanged += new System.EventHandler(this.blindSizeTrackBar_ValueChanged);
            // 
            // numberOfPlayersNumericUpDown
            // 
            this.numberOfPlayersNumericUpDown.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.numberOfPlayersNumericUpDown.Location = new System.Drawing.Point(381, 21);
            this.numberOfPlayersNumericUpDown.Maximum = new decimal(new int[] {
            2,
            0,
            0,
            0});
            this.numberOfPlayersNumericUpDown.Minimum = new decimal(new int[] {
            2,
            0,
            0,
            0});
            this.numberOfPlayersNumericUpDown.Name = "numberOfPlayersNumericUpDown";
            this.numberOfPlayersNumericUpDown.Size = new System.Drawing.Size(76, 26);
            this.numberOfPlayersNumericUpDown.TabIndex = 10;
            this.numberOfPlayersNumericUpDown.Value = new decimal(new int[] {
            2,
            0,
            0,
            0});
            this.numberOfPlayersNumericUpDown.ValueChanged += new System.EventHandler(this.numberOfPlayersNumericUpDown_ValueChanged);
            // 
            // potSizeNumericUpDown
            // 
            this.potSizeNumericUpDown.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.potSizeNumericUpDown.Increment = new decimal(new int[] {
            500,
            0,
            0,
            0});
            this.potSizeNumericUpDown.Location = new System.Drawing.Point(382, 72);
            this.potSizeNumericUpDown.Maximum = new decimal(new int[] {
            10000,
            0,
            0,
            0});
            this.potSizeNumericUpDown.Minimum = new decimal(new int[] {
            100,
            0,
            0,
            0});
            this.potSizeNumericUpDown.Name = "potSizeNumericUpDown";
            this.potSizeNumericUpDown.Size = new System.Drawing.Size(76, 26);
            this.potSizeNumericUpDown.TabIndex = 11;
            this.potSizeNumericUpDown.Value = new decimal(new int[] {
            1000,
            0,
            0,
            0});
            this.potSizeNumericUpDown.ValueChanged += new System.EventHandler(this.potSizeNumericUpDown_ValueChanged);
            // 
            // blindSizeNumericUpDown
            // 
            this.blindSizeNumericUpDown.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.blindSizeNumericUpDown.Increment = new decimal(new int[] {
            50,
            0,
            0,
            0});
            this.blindSizeNumericUpDown.Location = new System.Drawing.Point(381, 121);
            this.blindSizeNumericUpDown.Maximum = new decimal(new int[] {
            1000,
            0,
            0,
            0});
            this.blindSizeNumericUpDown.Minimum = new decimal(new int[] {
            10,
            0,
            0,
            0});
            this.blindSizeNumericUpDown.Name = "blindSizeNumericUpDown";
            this.blindSizeNumericUpDown.Size = new System.Drawing.Size(76, 26);
            this.blindSizeNumericUpDown.TabIndex = 12;
            this.blindSizeNumericUpDown.Value = new decimal(new int[] {
            50,
            0,
            0,
            0});
            this.blindSizeNumericUpDown.ValueChanged += new System.EventHandler(this.blindSizeNumericUpDown_ValueChanged);
            // 
            // nameErrorLabel
            // 
            this.nameErrorLabel.AutoSize = true;
            this.nameErrorLabel.ForeColor = System.Drawing.Color.Red;
            this.nameErrorLabel.Location = new System.Drawing.Point(243, 275);
            this.nameErrorLabel.Name = "nameErrorLabel";
            this.nameErrorLabel.Size = new System.Drawing.Size(170, 20);
            this.nameErrorLabel.TabIndex = 13;
            this.nameErrorLabel.Text = "Need to enter a name";
            this.nameErrorLabel.Visible = false;
            // 
            // timeBasedCheckBox
            // 
            this.timeBasedCheckBox.AutoSize = true;
            this.timeBasedCheckBox.Cursor = System.Windows.Forms.Cursors.Hand;
            this.timeBasedCheckBox.Location = new System.Drawing.Point(148, 184);
            this.timeBasedCheckBox.Name = "timeBasedCheckBox";
            this.timeBasedCheckBox.Size = new System.Drawing.Size(121, 24);
            this.timeBasedCheckBox.TabIndex = 14;
            this.timeBasedCheckBox.Text = "Time Based";
            this.timeBasedCheckBox.UseVisualStyleBackColor = true;
            this.timeBasedCheckBox.CheckedChanged += new System.EventHandler(this.timeBasedCheckBox_CheckedChanged);
            // 
            // roundBasedCheckBox
            // 
            this.roundBasedCheckBox.AutoSize = true;
            this.roundBasedCheckBox.Cursor = System.Windows.Forms.Cursors.Hand;
            this.roundBasedCheckBox.Location = new System.Drawing.Point(266, 184);
            this.roundBasedCheckBox.Name = "roundBasedCheckBox";
            this.roundBasedCheckBox.Size = new System.Drawing.Size(129, 24);
            this.roundBasedCheckBox.TabIndex = 15;
            this.roundBasedCheckBox.Text = "Round based";
            this.roundBasedCheckBox.UseVisualStyleBackColor = true;
            this.roundBasedCheckBox.CheckedChanged += new System.EventHandler(this.roundBasedCheckBox_CheckedChanged);
            // 
            // blindIncreaseNumericUpDown
            // 
            this.blindIncreaseNumericUpDown.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.blindIncreaseNumericUpDown.Increment = new decimal(new int[] {
            5,
            0,
            0,
            0});
            this.blindIncreaseNumericUpDown.Location = new System.Drawing.Point(379, 220);
            this.blindIncreaseNumericUpDown.Maximum = new decimal(new int[] {
            60,
            0,
            0,
            0});
            this.blindIncreaseNumericUpDown.Name = "blindIncreaseNumericUpDown";
            this.blindIncreaseNumericUpDown.Size = new System.Drawing.Size(76, 26);
            this.blindIncreaseNumericUpDown.TabIndex = 17;
            this.blindIncreaseNumericUpDown.Value = new decimal(new int[] {
            20,
            0,
            0,
            0});
            this.blindIncreaseNumericUpDown.Visible = false;
            this.blindIncreaseNumericUpDown.ValueChanged += new System.EventHandler(this.blindIncreaseNumericUpDown_ValueChanged);
            // 
            // blindIncreaseTrackBar
            // 
            this.blindIncreaseTrackBar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.blindIncreaseTrackBar.Location = new System.Drawing.Point(132, 220);
            this.blindIncreaseTrackBar.Margin = new System.Windows.Forms.Padding(4);
            this.blindIncreaseTrackBar.Maximum = 60;
            this.blindIncreaseTrackBar.Name = "blindIncreaseTrackBar";
            this.blindIncreaseTrackBar.Size = new System.Drawing.Size(240, 56);
            this.blindIncreaseTrackBar.TabIndex = 16;
            this.blindIncreaseTrackBar.Value = 20;
            this.blindIncreaseTrackBar.Visible = false;
            this.blindIncreaseTrackBar.ValueChanged += new System.EventHandler(this.blindIncreaseTrackBar_ValueChanged);
            // 
            // SettingsForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.ClientSize = new System.Drawing.Size(469, 418);
            this.Controls.Add(this.blindIncreaseNumericUpDown);
            this.Controls.Add(this.blindIncreaseTrackBar);
            this.Controls.Add(this.roundBasedCheckBox);
            this.Controls.Add(this.timeBasedCheckBox);
            this.Controls.Add(this.nameErrorLabel);
            this.Controls.Add(this.blindSizeNumericUpDown);
            this.Controls.Add(this.potSizeNumericUpDown);
            this.Controls.Add(this.numberOfPlayersNumericUpDown);
            this.Controls.Add(this.blindSizeTrackBar);
            this.Controls.Add(this.potSizeTrackBar);
            this.Controls.Add(this.numberOfPlayersTrackBar);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.textboxName);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.buttonStartGame);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "SettingsForm";
            this.Text = "Settings";
            ((System.ComponentModel.ISupportInitialize)(this.numberOfPlayersTrackBar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.potSizeTrackBar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.blindSizeTrackBar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numberOfPlayersNumericUpDown)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.potSizeNumericUpDown)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.blindSizeNumericUpDown)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.blindIncreaseNumericUpDown)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.blindIncreaseTrackBar)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button buttonStartGame;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox textboxName;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TrackBar numberOfPlayersTrackBar;
        private System.Windows.Forms.TrackBar potSizeTrackBar;
        private System.Windows.Forms.TrackBar blindSizeTrackBar;
        private System.Windows.Forms.NumericUpDown numberOfPlayersNumericUpDown;
        private System.Windows.Forms.NumericUpDown potSizeNumericUpDown;
        private System.Windows.Forms.NumericUpDown blindSizeNumericUpDown;
        private System.Windows.Forms.Label nameErrorLabel;
        private System.Windows.Forms.CheckBox timeBasedCheckBox;
        private System.Windows.Forms.CheckBox roundBasedCheckBox;
        private System.Windows.Forms.NumericUpDown blindIncreaseNumericUpDown;
        private System.Windows.Forms.TrackBar blindIncreaseTrackBar;
    }
}
